### ISSUE TITLE
[Request]: Support to detect GeForce Now

### ISSUE THREAD

**Issue by MinecraftNight4** [lieuweberg/rich-destiny#12]
The program works very well, but it would be great if support for detecting Destiny 2 on GeForce Now is added.

Some people create a script in AutoHotKey to force Rich-Destiny to be forced to run, but I wanted to ask if it would be possible to make this available in the native program.

**Comment by lieuweberg** [comment]
The issue is that there is no reliable way to easily detect if someone is playing specifically Destiny 2 on GFN, as playing another game on GFN would still just show . I was working on a thing which also would have added GFN and console support, but it was on the backburner because of other more important changes I was releasing.

If you only play Destiny on GFN, you can try to build the program yourself and swap references to "destiny2.exe" with "geforcenow.exe" (or whatever the GFN executable name is). I may however just add an option to enable GFN detection for this some day.

**Comment by MinecraftNight4** [comment]
Hmm, that's what I assumed. Well, I guess I'll close this for now, at least until I find an easy way to specifically detect that GFN is streaming Destiny 2.

Anyway, thanks for the answer!
